scheduling:
  initial-delay-get: 10000
  fixed-delay-get: 7200000
  initial-delay-purge: 3600000
  fixed-delay-purge: 7200000

altinn:
  service-code: service-code
  system-username: username
  system-password: password
  download-queue-uri: https://tt02.altinn.no/ArchiveExternal/DownloadQueueExternalBasic.svc
  attachment-data-streamed-uri: https://tt02.altinn.no/ArchiveExternal/ServiceOwnerArchiveExternalStreamedBasic.svc

spring:
  data:
    mongodb:
      database: altinn
      port: 27017