scheduling:
  initial-delay: 5000
  fixed-delay: 7200000

altinn:
  service-code: service-code
  system-username: username
  system-password: password
  download-queue-uri: https://www.altinn.no/ArchiveExternal/DownloadQueueExternalBasic.svc
  attachment-data-streamed-uri: https://www.altinn.no/ArchiveExternal/ServiceOwnerArchiveExternalStreamedBasic.svc
